require('hbom.pack.oil')
-- require('hbom.pack.catppuccin')
require('hbom.pack.rose-pine')
require('hbom.pack.lsp')
require('hbom.pack.blink')
require('hbom.pack.which-key')
require('hbom.pack.fzf-lua')
require('hbom.pack.treesitter')
require('hbom.pack.autopairs')
